### ISSUE TITLE
🛑 Message API is down

### ISSUE THREAD

**Issue by thecoder876** [discord-html/Discord.html-Status#3]
In [`8610e9b`](https://github.com/discord-html/Discord.html-Status/commit/8610e9b2d1fd2a27250b4bf0e2044cfaab3b3bdd
), Message API (https://discordhtml-api.guacaplushy2.repl.co) was **down**:
- HTTP code: 404
- Response time: 375 ms

**Comment by thecoder876** [comment]
btw this automatically sends messages as me since i used my access token

**Comment by guacaplushy** [comment]
> btw this automatically sends messages as me since i used my access token

ok
